### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [32, 3, 1, 1], expected input[64, 2, 207, 13] to have 3 channels, but got 2 channels instead

### ISSUE THREAD

**Issue by zycode1561** [CYBruce/STAWnet#2]
Thanks for your coding!
I run the train.py and found this error.
Who can help me ?
Thanks

**Comment by CYBruce** [comment]
What data do you use? Would you please describe the dimension of your input data? Try`python train.py --in_dim 1 --batch_size 32` instead?

**Comment by MachineryZ** [comment]
Same problem here. And  `python train.py --in_dim 1 --batch_size 32` cannot solve this problem

**Comment by MachineryZ** [comment]
I think he use the metr_la data @zycode1561 @CYBruce

**Comment by CYBruce** [comment]
Then try python train.py --in_dim 2. the reason is about the diff between input_dimension and the defined model dimension.
